### ISSUE TITLE
Broken Guest Auditor Link

### ISSUE THREAD

**Issue by remedcu** [yacademy/yacademy.github.io#24]
Website Link: https://yacademy.dev/
Broken Link: https://yacademy.dev/guest-auditor-program
Link of Broken Code: https://github.com/yacademy/yacademy.github.io/blob/main/index.md?plain=1#L32

I think the Guest Auditor Program has been wrapped for the time being, but the link is still present on the index page.

**Comment by aliatiia** [comment]
Thanks!
